gText_Birch_Welcome::
	.string "Greetings!\n"
	.string "Welcome to the world of Pokémon!\p"
	.string "I'm…{PAUSE 60} well, that doesn't matter.{PAUSE 60}\n"
	.string "Anyway…\p"
	.string "$"
gText_Birch_Pokemon::
	.string "This world is inhabited by\n"
	.string "creatures known as Pokémon.{PAUSE 96}\p"
	.string "$"
gText_Birch_MainSpeech::
	.string "People and Pokémon, live and support\n"
	.string "each other.\p"
	.string "Some people play with Pokémon,\n"
	.string "some people study them.\p"
	.string "Others even battle their Pokémon\n"
	.string "and strive to be champions.\p"
	.string "$"
gText_Birch_RedIntro::
	.string "This is Red.\p"
	.string "Hailing from Pallet Town in the\n"
	.string "Kanto region, he successfully became\l"
	.string "the region's Pokémon Champion…\p"
	.string "…while also taking down the corrupt\n"
	.string "Team Rocket.\p"
	.string "$"
gText_Birch_GoldIntro::
	.string "Meet Gold.\p"
	.string "Also a young trainer, he left home\n"
	.string "from New Bark in Johto, and\l"
	.string "worked his way to the top…\p"
	.string "…challenging many tough and trouble-\n"
	.string "some foes along the way.\p"
	.string "$"
gText_Birch_AndYouAre::
	.string "…but you!\n"
	.string "You, too, are destined for greatness!\p"
	.string "Why not tell me a little about\n"
	.string "yourself?\p"
	.string "$"
gText_Birch_ChooseModel::
	.string "Select a character model.$"
gText_Birch_ConfirmLook::
	.string "Is this the look you want?$"
	
gText_Birch_WhatsYourName::
	.string "Finally, could you please tell me\n"
	.string "your name?$"
	
gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own Pokémon story is\n"
	.string "about to unfold.\p"
	.string "You'll face fun times and tough\n"
	.string "challenges.\p"
	.string "A world of dreams and adventures\n"
	.string "with Pokémon awaits! Let's go!\p"
	.string "I'm sure I'll see you later!\p"
	.string "$"




@ gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

@ gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

@ gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

@ gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

@ gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	@ .string "Ah, okay!\p"
	@ .string "You're {PLAYER}{KUN} who's moving to my\n"
	@ .string "hometown of LITTLEROOT.\l"
	@ .string "I get it now!\p"
	.string "$"

@ gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"

gText_Skyrim_IntroLine1::
	.string "{PAUSE 60}Hey,{PAUSE 30} you.{PAUSE 50} You're finally awake.\p"
	.string "You were trying to cross the border,\n"
	.string "right?\p"
	.string "Walked right into that\n"
	.string "Imperial ambush, same as us.\p$"
gText_Skyrim_AprilFools::
	.string "{CLEAR_TO 60}Happy April Fools\n"
	.string "{CLEAR_TO 59}from RainbowDevs$"
gText_Skyrim_ComingSoon::
	.string "{CLEAR_TO 26}(The real release of Prism 0.95\n"
	.string "{CLEAR_TO 18}is coming really soon. We promise.)$"

